### ISSUE TITLE
G&P | Extract Stories from OBS PnP

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#2228] opened 2021-10-20 19:29 UTC
Create a new PnP Extract for Planning Goals and Tracking Progress using the new Oral Storytelling PnP.

This is similar to the existing PnP but only has 4 steps.

When this is added we should also add the option to select all Methodologies of the Oral Storying Approach on the Plan Upload dialogue.

A copy of the Storytelling PnP can be accessed here: https://docs.google.com/spreadsheets/d/12eUOJVfONErDXwCjuf_UykmxQFLIz4sx/edit?usp=sharing&ouid=103781340369405856620&rtpof=true&sd=true

A training video of this version can be accessed here: https://vimeo.com/613875535/06c052540a

**Comment by sethmcknight** [comment] 2021-11-10 17:41
After reviewing with @CarsonF we'll focus on only the Story Goals here and leave the Other Goals (Sustainability Metrics) for later (#2275)

**Comment by CarsonF** [comment] 2021-11-11 01:01
I've got an `obs-pnp` branch started for this. Here's what's done and what's left. I think I'd like/need to hand it off at this point.
- [x] Progress
  - [X] Detect & extract progress data from OBS PnPs
  - [x] Update progress data by matching existing products with the same story name
  - ~Extract/update sustainability progress~
    This doesn't follow what we have available right. Progress is communicated by saying X people are "on track" or "behind" for this goal. Since these are approximations & relative measurements, tracking this needs to be given more thought.
- [ ] Planning (Product Creation/Updates)
  - [x] Detect & extract product data from OBS PnPs
  - [ ] Match extracted product rows to existing product's story name
    - [ ] Handle changes in story names. Since it's common for people to start with 40 "unknown" stories and figure out what they actually are later, we need to be able to handle this too. Maybe this is based on the index offset? That would need to be persisted in the DB internally some how. This would break if users moved rows around.
  - [ ] Create/Update produces field with Story by name (find existing or create new)
  - [ ] Extracted `scripture` can be assigned to `scriptureReferencesOverride` field
  - [ ] Total verses is extracted for completeness, but I'm not sure there's anything to do with it. In some cases it's just a helper for users based on the scripture references. In other cases total verses is specified manually, like with "Composite" scripture. We don't have a way currently to do just a total verse count. Current thought is to just ignore this? @sethmcknight thoughts?
  - [ ] New `composite` boolean field. This represents whether the "Story" being referenced is multiple composite stories. My first thought is this should exist on the `Story` object, instead of `DerivativeScriptureProduct`, but if it's not the same for all usages of the story, that's a problem. @sethmcknight thoughts?
  - [ ] `steps` & `note` fields applied as `steps` & `completionDescription`
  - ~Connect sustainability trainees as other products~
    Omitting for now as we don't have a way to track progress

**Comment by sethmcknight** [comment] 2021-11-11 19:05
@Carson see below:

>   * [ ]  Total verses is extracted for completeness, but I'm not sure there's anything to do with it. In some cases it's just a helper for users based on the scripture references. In other cases total verses is specified manually, like with "Composite" scripture. We don't have a way currently to do just a total verse count. Current thought is to just ignore this? @sethmcknight thoughts?

I'm ok with ignoring for now if we need too, but we should create an issue for this in the backlog and revisit. Is this just blocked by SeedCompany/cord-field#997 ?

>   * [ ]  New `composite` boolean field. This represents whether the "Story" being referenced is multiple composite stories. My first thought is this should exist on the `Story` object, instead of `DerivativeScriptureProduct`, but if it's not the same for all usages of the story, that's a problem. @sethmcknight thoughts?

I'm not sure I completely follow, but we could have 2 different stories, one that is a `composite` and one that is not. I'm good having this field on anything object related to the `Story` Goal type.

Let me know if we need to talk this through more.

**Comment by CarsonF** [comment] 2021-11-18 17:47
> I'm ok with ignoring for now if we need too, but we should create an issue for this in the backlog and revisit. Is this just blocked by [SeedCompany/cord-field#997](https://github.com/SeedCompany/cord-field/issues/997) ?

No not blocked by that. We currently only have "unspecified scripture portion" (book & verse count) on scripture products. Book name is required in that. If we wanted to use that here for "composite" we could but we'd need to make book name optional. That would have implications in the scripture form since we base the total off of the book selected currently.

We also pick one or the other (known or unknown), and we'd would probably want to do the same here. So if the spreadsheet had "Genesis 1" but the total verses wasn't 31 we'd ignore that known reference for an unspecified one.

**Comment by CarsonF** [comment] 2021-11-18 20:19
Updated main comment to reflect decisions with @sethmcknight

**Comment by CarsonF** [comment] 2021-12-18 00:24
Instead of matching based on story name we are going to match based on the row number (column P). This will be saved as an `order` field, which can be used for custom ordering in future. @daniel-leod is implementing with #2314

**Comment by sethmcknight** [comment] 2021-12-22 14:38
This is looking good so far! The stories & story progress look like they are extracting correctly (just waiting on the `order` field).

Outstanding is the Planned/Actual Progress & Variance 
<img width="790" alt="Screen Shot 2021-12-22 at 7 36 28 AM" src="https://user-images.githubusercontent.com/7377802/147109275-6e01b000-d98a-4df5-bc96-c681a7224164.png">

**Comment by CarsonF** [comment] 2021-12-22 16:40
The cumulative summary data extraction should already be setup for OBS. You sure you are uploading to the correct report that matches the fiscal year row?

**Comment by sethmcknight** [comment] 2021-12-22 16:55
Yep, Q4 2021... see here: https://dev.cordfield.com/projects/guwOWybFAB4/engagements/FGnaCnDPrqR/reports/progress/KZgM0ImlzRo

**Comment by CarsonF** [comment] 2021-12-22 17:24
Just tweaked the fiscal year row matching for OBS PnP (e71c564). Give it a go after it deploys.

**Comment by sethmcknight** [comment] 2021-12-22 17:44
> Just tweaked the fiscal year row matching for OBS PnP ([e71c564](https://github.com/SeedCompany/cord-api-v3/commit/e71c5646e2a639589f1658007f143272c9863740)). Give it a go after it deploys.

Awesome, looks good!

**Closed** 2022-01-06 16:55 UTC
Labels: G&P
