### ISSUE TITLE
G&P | Goals of type `Other` can't be tracked if Methodology is not selected

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#2249] opened 2021-11-01 14:47 UTC
When a user creates an `Other` Goal, selects the Progress Measurement and Step of Completed they are able to create the Goal. 

When the user visits the Goal Details to view/track progress they get a message that "Product does not have any steps".

If a user selecta a Methodology the app functions as expected and they can see the Step and record progress.

We need to allow users to view the step and track progress without a Methodology being selected.

**Comment by CarsonF** [comment] 2021-11-03 14:41
Duplicate of https://github.com/SeedCompany/cord-field/issues/992

**Closed** 2021-11-03 23:14 UTC
Labels: bug
