### ISSUE TITLE
Project > Get all projects > query projects($input: ProjectListInput!) > Filter by 'mine' returns same project results for both 'true' and 'false' filter value

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#768] opened 2020-07-17 13:01 UTC
**Describe the bug**
Project > Get all projects > query projects($input: ProjectListInput!) > Filter by 'mine' returns same project results for both 'true' and 'false' filter value. 

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Projects results are returned as per filter input of 'mine' i.e If mine = false then it should not return Projects created by logged in User.

**Actual Result**
 Filter by 'mine' returns same project results for both 'true' and 'false' filter value. See video - https://drive.google.com/file/d/1NsbGvR6psSgGMge0AAd6QQNcFd9OevqV/view?usp=drivesdk

GraphQL Query( mine - false ):
![image](https://user-images.githubusercontent.com/5212585/87788247-ab9c9900-c85a-11ea-9dc2-2a301a78fbff.png)

GraphQL Query( mine - true ):
![image](https://user-images.githubusercontent.com/5212585/87788354-d686ed00-c85a-11ea-986e-d33085fdb2d4.png)

**Query and Input File**
[projects_FILTERmineIssue.txt](https://github.com/SeedCompany/cord-api-v3/files/4937901/projects_FILTERmineIssue.txt)

CordAPIV3# bbf864f

**Comment by reneepe** [comment] 2020-07-17 21:57
Bug verified. The same results are displayed regardless of the filter setting.

![image](https://user-images.githubusercontent.com/38309285/87833779-afc6b780-c856-11ea-8df5-9b4be3663adf.png)
![image](https://user-images.githubusercontent.com/38309285/87833844-d84eb180-c856-11ea-9ac5-7e1395cdbc61.png)

**Comment by reneepe** [comment] 2020-07-17 22:17
This is a duplicate of https://github.com/SeedCompany/cord-api-v3/issues/643

**Closed** 2020-07-17 22:31 UTC
Labels: bug, duplicate
