### ISSUE TITLE
Sudest Project Load Error: Int cannot represent non-integer value: 68015.98

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-api-v3#1710] opened 2021-03-04 19:05 UTC
Seth's best guess is that it is an error with one of the budget records. If so we either need to clean data & enforce integers or change that to floats. I believe from talking with Phil those fields need to stay integers though.

User details: https://github.com/SeedCompany/management/issues/81

![110006641-e5d28200-7ce7-11eb-935e-b63c114867f2](https://user-images.githubusercontent.com/5691814/110016260-d1e04d80-7cf2-11eb-841b-da9f2c959392.png)

**Comment by CarsonF** [comment] 2021-03-04 19:39
Fixed by #1708

**Closed by CarsonF** 2021-03-04 19:39 UTC
Labels: bug

**Comment by ParkeBrown** [comment] 2021-03-04 21:50
@CarsonF I think this will get fixed by the code but it appears the merge hasn't taken effect. Do you expect it to before you folks wrap for the week?

**Comment by CarsonF** [comment] 2021-03-05 00:08
Thanks for catching that @ParkeBrown. The deployment was failing due to another change. I've fixed that and confirmed it's live now.

**Comment by ParkeBrown** [comment] 2021-03-05 01:24
Thanks! I see the project.
