### ISSUE TITLE
[BUG] Set FinancialReportingType on Partner

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1517] opened 2020-11-05 18:58 UTC
Administrator, Controller and Financial Analyst roles should be able to update the Financial Reporting Types on Partners.

Currently it looks like the update is accepted but the data is never updated/changed.

**Comment by zkhin** [comment] 2020-11-10 20:16
@sethmcknight I cannot reproduce this bug on the latest master. Can you write the steps in detail to repro? Thanks

**Comment by elisabeth-sorrell** [comment] 2020-12-15 20:19
@sethmcknight Tried to reproduce, as well. created users with controller, financial analyst, and with default admin user created a partner with each. Toggled the FinancialReporting type of each and checked with each user. The only time I wouldn't be able to see the update was when I didn't refresh the page correctly. Any way to check if this is still an issue?
FYI, @ParkeBrown

**Comment by sethmcknight** [comment] 2021-01-05 17:46
@elisabeth-sorrell thanks for reminding me about this today! I need to get access to the beta environment again and then I'll check on this.

**Comment by michaelmarshall** [comment] 2021-01-05 19:25
@sethmcknight we've merged some PRs. please verify this is done.

**Comment by sethmcknight** [comment] 2021-01-13 17:32
@elisabeth-sorrell @michaelmarshall yes, it looks like this has been resolved.

**Closed** 2021-01-13 17:32 UTC
Labels: bug
