### ISSUE TITLE
query projects > Getting "Could not find project member" error after creating the "Internship" Project

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1563] opened 2020-11-27 13:25 UTC
**Roles:** ProjectManager 

**Describe the bug**
query projects > Getting `Could not find project member` error after creating the `Internship` Project

**Steps to Reproduce**
1. Login as a project manager
2. Create a project with `Internship` type 
3. Hit the request of `query projects`

**Expected Result**
Projects listing should be returned.

**Actual Result**
Getting `Could not find project member` error after creating the `Internship` Project
See video - https://drive.google.com/file/d/1gOc_tWxMkzcwUxxDQf2f3vof0G2pibud/view?usp=drivesdk

**GraphQL Query (projects ):**
![image](https://user-images.githubusercontent.com/5212585/100452743-beb05700-30df-11eb-8140-b8232a0e9e97.png)

**GraphQL response**
```
{
    "errors": [
        {
            "message": "Could not find project member",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "name": "NotFoundException",
                    "status": 400,
                    "field": "projectMember.id",
                    "stacktrace": [
                        "at ProjectMemberService.readOne (components\\project\\project-member\\project-member.service.ts:198:13)",
                        "at async Promise.all (index 0)",
                        "at Object.runListQuery (core\\database\\results\\lists.ts:24:12)",
                        "at ProjectMemberService.list (components\\project\\project-member\\project-member.service.ts:318:12)",
                        "at ProjectService.listProjectMembers (components\\project\\project.service.ts:848:20)"
                    ]
                },
                "codes": [
                    "INTERNAL_SERVER_ERROR",
                    "Server"
                ]
            },
            "locations": [
                {
                    "line": 584,
                    "column": 7
                }
            ],
            "path": [
                "projects",
                "items",
                0,
                "team"
            ]
        }
    ],
```

**Query and Input File**
[NotFoundErrorInProjects.txt](https://github.com/SeedCompany/cord-api-v3/files/5607931/NotFoundErrorInProjects.txt)

CordAPIV3# 73f6e558

**Comment by elisabeth-sorrell** [comment] 2020-12-17 20:55
@iPiyushPatel Just tried to verify this. Kept getting an error for the `canCreate` property because it was null. Deleted all of the `canCreate`s in the output and works. Not sure why I can't reproduce the error....?

**Comment by iPiyushPatel** [comment] 2020-12-18 11:51
Hi @elisabeth-sorrell 
Yes i can not replicate the issue when I remove the field `cancreate` from output but I can replicate with it
Can you investigate?

**Comment by elisabeth-sorrell** [comment] 2020-12-18 17:02
@iPiyushPatel thanks for double checking. I'll totally get on this. I'm just not sure how you don't get the 'cannot return null value' error with `canCreate`, but maybe my roles were messed up or something.

**Comment by elisabeth-sorrell** [comment] 2020-12-18 23:34
Note: blocking https://github.com/SeedCompany/cord-api-v3/issues/1580

**Comment by elisabeth-sorrell** [comment] 2020-12-31 22:05
PR: https://github.com/SeedCompany/cord-api-v3/pull/1589

**Comment by elisabeth-sorrell** [comment] 2021-01-05 20:46
@iPiyushPatel PR is merged in. Can you verify that this is working in latest develop branch when you get a chance?

**Comment by iPiyushPatel** [comment] 2021-01-06 09:08
Hi,@elisabeth-sorrell 
I have verified on the latest develop 080a4abd and it's working fine.

**Comment by elisabeth-sorrell** [comment] 2021-01-06 17:19
@ParkeBrown Putting into Sprint Closed since it's verified.

**Closed** 2021-01-28 17:13 UTC
Labels: bug
