### ISSUE TITLE
Get all Partnerships  > query partnerships($input: PartnershipListInput!) > Created Partnership item returned twice times in partnership listing

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#717] opened 2020-07-10 05:42 UTC
**Describe the bug**
Get all Partnerships  > query partnerships($input: PartnershipListInput!) > Created Partnership item returned twice times in partnership listing

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Unique object with unique details should be returned in partnership listing. e.g. Id has to be unique etc.

**Actual Result**
Created Partnership item returned twice times in partnership listing i.e. one record per Id. See video - https://www.awesomescreenshot.com/video/369337?key=2c018544748a6de90a2cef6703a5dedd

GraphQL Query ( createProject ):
![image](https://user-images.githubusercontent.com/5212585/87119733-701f2f00-c29c-11ea-8424-be0cde4b93f3.png)

GraphQL Query ( createPartnership ):
![image](https://user-images.githubusercontent.com/5212585/87119773-8d53fd80-c29c-11ea-8006-bb67ea77a671.png)

GraphQL Query ( partnerships ):
![image](https://user-images.githubusercontent.com/5212585/87119840-be343280-c29c-11ea-9328-886bc8288c7d.png)

**Query and Input File**
[createProject_PartnerDuplicateISSUE.txt](https://github.com/SeedCompany/cord-api-v3/files/4901178/createProject_PartnerDuplicateISSUE.txt)
[createPartnership_PartnerDuplicateISSUE.txt](https://github.com/SeedCompany/cord-api-v3/files/4901180/createPartnership_PartnerDuplicateISSUE.txt)
[partnerships_PartnerDuplicateISSUE.txt](https://github.com/SeedCompany/cord-api-v3/files/4901181/partnerships_PartnerDuplicateISSUE.txt)

CordAPIV3# 8476112

**Comment by CarsonF** [comment] 2020-07-10 12:24
Duplicate of #691?

**Comment by iPiyushPatel** [comment] 2020-07-10 12:27
Hi @CarsonF 
To be honest, I had confusion about this, but to have a focus on this, I put down a separate bug for this.  May be different as user level but same at coding level, Up to you :)

**Closed** 2020-07-14 14:24 UTC
