### ISSUE TITLE
Add new field to cf3.LanguagEngagements.prod for Domo

### ISSUE THREAD

**Issue by kjones140** [SeedCompany/cord-api-v3#2294] opened 2021-11-22 17:04 UTC
Devops,
Please add the new field "Open to Investor Visit" that is part of the LanguageEngagement  to the CF3.LanguageEngagements.PROD dataset in Domo.  Please name the field as OpenToVisitsFlag and provide a value of Y or N.

**Comment by ParkeBrown** [comment] 2021-11-22 17:09
@sethmcknight as seen in Slack

**Comment by CarsonF** [comment] 2021-11-22 17:17
Duplicate of https://github.com/SeedCompany/seed-api/issues/194

**Closed by CarsonF** 2021-11-22 17:17 UTC
Labels: DA Request
