### ISSUE TITLE
mutation createProduct > Getting "failed to create default product" error on invalid id input to 'engagementId' field

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#968] opened 2020-08-17 09:18 UTC
**Describe the bug**
mutation createProduct > Getting "failed to create default product" error on invalid id input to 'engagementId' field.

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request.

**Expected Result**
Better error/validation message should be displayed for invalid id input to 'engagementId' field.

**Actual Result**
Getting "failed to create default product" error on invalid id input to 'engagementId' field.
See video - https://drive.google.com/file/d/1g3ETkULWUTLqqHc6D4IH0GT3aghQjE3c/view?usp=drivesdk

GraphQL Query ( createProduct-error ):
![image](https://user-images.githubusercontent.com/5212585/90377825-2cd38f80-e096-11ea-991f-8174b6f09092.png)

GraphQL Query ( createProduct):
![image](https://user-images.githubusercontent.com/5212585/90377960-64dad280-e096-11ea-8868-5bea1f5ad974.png)

**Query and Input File**
[createProduct_FAILEDtoCreate_ERR.txt](https://github.com/SeedCompany/cord-api-v3/files/5083246/createProduct_FAILEDtoCreate_ERR.txt)

Environment: Integration

**Note**
I can replicate the same in the local environment on the latest master # 541da078

**Comment by tjgersho** [comment] 2020-08-18 18:07
I think this issue is a duplicate of #964 so should be closed.

**Comment by reneepe** [comment] 2020-09-11 23:53
Duplicate of #964

**Closed** 2020-09-11 23:53 UTC
Labels: bug, duplicate
