### ISSUE TITLE
mutation CreateProduct > Getting "No book matched" error while 'produces' field is not provided

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#942] opened 2020-08-14 03:02 UTC
**Describe the bug**
mutation CreateProduct > Getting "No book matched" error while 'produces' field is not provided

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request.

**Expected Result**
Product should be created or a Proper field validation message should be displayed.

**Actual Result**
Getting "No book matched" error while 'produces' field is not provided.
See video - https://drive.google.com/file/d/1M_uuSUG2zXNLozIVPoqeC9zUt6DEgWbv/view?usp=drivesdk

GraphQL Query ( CreateProduct ):
https://drive.google.com/file/d/1nTnh_JBZ-Q_TKqkDNUzoILcIAw1w47Wx/view?usp=sharing

**Query and Input File**
https://drive.google.com/file/d/1DQa9SNVfyFc-dkvD7gVn1sCL7_45VQdF/view?usp=sharing

CordAPIV3# 544d30c6

**Comment by tjgersho** [comment] 2020-08-14 19:30
Usually, produces and scriptureRef should not be inputted together. One of them should be ignored. 
Currently, produces's priority is higher than scriptureRef. So if produces is inputted with scRef, scriptureRef will be ignored and DerivativeScriptureProduct will be created. DerivativeScriptureProduct always has empty scriptureRef which has no meaning.

But if only scriptureRef is inputted, it checks if the book/chapter/verse is valid, then if valid, DirectScriptureProduct will be created with that scriptureRef. 

So the expected result needs to be more detailed to show the validation error?
`'No book matched "' + name + '"'`

**Comment by CarsonF** [comment] 2020-11-10 17:24
@iPiyushPatel feel free to reopen if this is still a problem

**Comment by iPiyushPatel** [comment] 2020-11-13 10:32
@CarsonF @michaelmarshall 
I've tested on latest master 8c61fd8c and getting `Verse 407 of Genesis 3 does not exist` error while 'produces' field is not provided.
See Video: https://drive.google.com/file/d/1WxduUZyMDtCHFcaeLclzKZBfqz3UmSUk/view?usp=drivesdk

**Comment by elisabeth-sorrell** [comment] 2020-12-15 20:52
@ParkeBrown Looks like a solution has already been merged in. See https://github.com/SeedCompany/cord-api-v3/pull/1069

**Comment by ParkeBrown** [comment] 2020-12-16 19:58
@iPiyushPatel would you verify this fix in your next round of work?

**Comment by iPiyushPatel** [comment] 2020-12-17 10:04
@elisabeth-sorrell @ParkeBrown 
I've tested on the latest master 8c61fd8 and getting `"Verse 415 of Genesis 3 does not exist"` error while 'produces' field is not provided.
See video: https://drive.google.com/file/d/1F3SDyQosKJoPmugW_Cp7ob13jrqn-Oht/view?usp=drivesdk

**Comment by elisabeth-sorrell** [comment] 2020-12-17 16:51
@iPiyushPatel tried verifying on latest develop but getting "Variable \"$input\" of required type \"CreateProductInput!\" was not provided."
Mutation:
```mutation CreateProduct($input: CreateProductInput!) {
  createProduct(input: $input) {
    product {
      id
      createdAt
      approach
      legacyType
      mediums {
        value
        canEdit
        canRead
      }
      purposes {
        value
        canEdit
        canRead
      }
      methodology {
        value
        canEdit
        canRead
      }
      scriptureReferences {
        value {
          start {
            book
            chapter
            verse
            label
          }
          end {
            book
            chapter
            verse
            label
          }
          label
          totalVerses
        }
        canEdit
        canRead
      }
    }
  }
}```

input:

```{
  "input": {
    "product": {
      "produces" : "L2G3YOWJPiZ",
      "engagementId": "JIVRSXsFRip",
      "mediums": ["Film"],
      "purposes": ["ChurchLife"],
      "methodology": "Paratext",
      "scriptureReferencesOverride":[],
      "scriptureReferences": {
        "start": {
          "book": "Genesis",
          "chapter": 40,
          "verse": 1
        },
        "end": {
          "book": "Genesis",
          "chapter": 41,
          "verse": 1
        }
      }
    }
  }
}```

**Comment by iPiyushPatel** [comment] 2020-12-18 12:17
@elisabeth-sorrell 
I've tested on the latest develop a99ebf10 and not getting any error.
I've used the same input with a change in only `produces`, `engagementId`, and `mediums` fields. 
I think "Film" is not a part of enum `ProductMedium` as per the schema.

**Comment by elisabeth-sorrell** [comment] 2020-12-18 22:04
@ParkeBrown Okay, going to close this then since there's no more error

**Closed** 2021-01-28 18:04 UTC
Labels: bug
